### ISSUE TITLE
mass records performance...

### ISSUE THREAD

**Issue by johnhuang669** [marklio/LinqToStdf#10]
hi 
I find the  method "GetChildRecords(this Prr prr)"  performance is not good that STDF is over 500MB...

I think the problem is  "Before(this StdfRecord record)" and "After(this StdfRecord record)"
they use more and more data to filter... cause the performance is slow

how to solve it  please help me

**Comment by marklio** [comment]
There is a branch called IndexingReconciliation that allows you to increase the performance of queries like that. It can build indexes for part records and their children. Then, it isn't iterating over ALL the records, just the ones between part records for a particular insertion (It still has to filter to match the part id if it is multi-site).

**Comment by marklio** [comment]
Actually, I'm not certain of the state of that branch. Let me know if you run into problems.

**Comment by johnhuang669** [comment]
I user the branch of master.

" Before(this StdfRecord record)" will get more and more stream , so the performance is  more and more slower

**Comment by johnhuang669** [comment]
so if i want get all the Ptr testdata,how could I do?

like that?

`var arrPrrData = stdfData.OfExactType<Prr>()();
foreach (var item in arrPrrData)
{
    
    var arrTestData = item.GetChildRecords().OfExactType<Ptr>().ToDictionary(o => o.TestNumber, o => o.Result.Value);

    foreach (var test in arrTestItem)
    {
      
    }

 
}`

**Comment by johnhuang669** [comment]
could you help me.....please

**Comment by marklio** [comment]
Sorry. My suggestion was to use the indexing branch where this magic happens for you. If you want to do the indexing yourself with master, just make a single pass and index, then use your own index to get at the records. You can see how the indexing stuff works by looking at that code and using parts that you need. The main part is here:

https://github.com/marklio/LinqToStdf/blob/9525a5ebefc2a7866b548c555b2a49af7e8c1451/Main/LinqToStdf/Indexing/V4StructureIndexingStrategy.cs#L120

The ParentMap (https://github.com/marklio/LinqToStdf/blob/9525a5ebefc2a7866b548c555b2a49af7e8c1451/Main/LinqToStdf/Indexing/V4StructureIndexingStrategy.cs#L46) is a pretty reasonable way to index the records, but you can just shove them into a dictionary if you don't mind the overhead.

**Comment by johnhuang669** [comment]
how to use IndexRecords to get all records?

`  var stdfData = stdf.GetRecords().ToList();
  V4StructureIndexingStrategy v4 = new V4StructureIndexingStrategy();
  v4.IndexRecords(stdfData);`

**Comment by marklio** [comment]
You won't be able to use those as-is (unless, as I've suggested each time, you build from a branch that supports indexing, where this will happen automatically and part-based queries will be fast). You'll need to copy that code and index the records into your own datastructures to get the kind of perf you're looking for.

**Comment by marklio** [comment]
I have merged the indexing support into master. You might try building from master and setting StdfFile.IndexingStrategy to a V4StructureIndexingStrategy instance. There may be other tweaks you'll need to make this work.

**Comment by marklio** [comment]
I'm closing this now. Please let me know if you are still having problems with this.
