### ISSUE TITLE
Loading Mir.StartTime

### ISSUE THREAD

**Issue by miguelmpn** [marklio/LinqToStdf#11]
When loading one STDF file, if I look to the Mir.StartTime the milliseconds is always 0.
I'm also creating the file, so I know that when I add the DateTime to the StartTime it has the milliseconds.

Anything I can do to save/read it correctly?

**Comment by dingetje** [comment]
The time stamp in an STDF is a 4 byte *NIX time stamp (# of seconds since the "epoch 1/1/1970), so by default it does not support millisecond accuracy.

**Comment by marklio** [comment]
> The time stamp in an STDF is a 4 byte *NIX time stamp (# of seconds since the "epoch 1/1/1970), so by default it does not support millisecond accuracy.

This is correct. This is one of those "mismatches" between the .NET data types and the STDF data types. If you needed to smuggle a more precise time stamp in an STDF you could:

- Use a Gdr with generic data fields that encode a time stamp the way you want
- Use a Dtr and encode your timestamp with some text encoding
- Create a custom record type
- other creative uses of other records

**Comment by miguelmpn** [comment]
Thank you for your explanation dingetje and marklio... I actually had a brief look on the code and noticed that.
Thank you for your suggestions, your assistance and this library ;)
