### ISSUE TITLE
How and When maybe for java

### ISSUE THREAD

**Issue by guoxunbo** [marklio/LinqToStdf#14]
Hello guys.
    Does there has plan for support java?

**Comment by marklio** [comment]
Unfortunately, no. This project is the result of me having worked the first part of my career in the semiconductor industry, then moving into software and working for Microsoft on the .NET team. This represents the library I would have liked to have during my semiconductor years. A Java port would be tricky as this library leans heavily on .NET features. it would be easier to start from scratch on Java.
