### ISSUE TITLE
Example of how to use the Extension GetPrr?

### ISSUE THREAD

**Issue by miguelmpn** [marklio/LinqToStdf#15]
Hello, 

I have an StdfFile, can you show me an example of how to use the extension GetPrr?

`public static Prr GetPrr(this IHeadSiteIndexable record)`

**Comment by marklio** [comment]
GetPrr is an extension method over IHeadSiteIndexable, so it allows you to find the PRR record associated with with any record with head/site information (PIR, PTR, FTR, etc.). So, for example, if you have a ptr, you can do:
`var prr = ptr.GetPrr();`

Implementation-wise, it just walks records until if finds a PRR record with the same head/site info as the current record.

Feel free to re-open this if this doesn't answer your question.
