### ISSUE TITLE
MPR Results being clipped

### ISSUE THREAD

**Issue by mgoldste1** [marklio/LinqToStdf#27]
This is a weird one... Figured I'd try and get your thoughts on it.  The results array in MPR records is an array of R*4's according to the spec. 4 byte floating point number.  The parser saves it as a float because in c# a float is 4 bytes...

In our old stdf parser, it reads in a **-1.8033077**716827393 from the first float in the results array.  
In our terrible java utility it reads in a -1.8033078.  In LinqToStdf, it reads in a -1.8033078.  Notice it rounded it up, so it has to know its a longer number?

I grabbed this viewer here - https://github.com/noonchen/STDF-Viewer/releases/tag/V4.0.0 and in the options you can pick your precision.  I maxed it out.  That read in a -1.80330777168.  

So this parser is definitely clipping the data.  I ran a test in c#. 

float f = -1.8033077716827393f;
var castToDouble= (double)f;
double d = f;

When you inspect f there, it shows the clipped value, same as this parser. When you cast it to a double, suddenly it has the full precision. When you save it to a double, it also has the full precision.

For the results attribute -   "ArrayFieldLayout(FieldIndex = 8, FieldType = typeof(float), ArrayLengthFieldIndex = 6, RecordProperty = "Results", NameInSpec = "RTN_RSLT")"

You can't switch that to a double or it will error out.  I tried switching the results type from a float[] to double[] and while that doesnt error out, it doesn't fix it either...

I haven't dug into this part of the code much so I figured I'd see if you had any ideas on this one...  It's a serious misprocessing risk and honestly everyone using this project should update their code when we find a solution...

**Comment by mgoldste1** [comment]
short update... This is the start of my code for parsing die level data.

```
            var pirs = recs.OfExactType<Pir>();
            List<IEnumerable<StdfRecord>> dieGroupings = new();
            foreach (var record in pirs)
            {
                List<StdfRecord> singleDiesRecords = new();
                singleDiesRecords.Add(record);
                singleDiesRecords.AddRange(record.GetChildRecords());
                singleDiesRecords.Add(record.GetMatchingPrr()!);
                dieGroupings.Add(singleDiesRecords);
            }
            float f = dieGroupings.First().OfExactType<Mpr>().First().Results.First();
            double d = (double)f;
```
d contains the full number so the float does have all the data in it... it just isnt accessible until you cast it to a double.  You'd think it'd clip it when it makes the float if a float can only store 9 digits of precision (https://learn.microsoft.com/en-us/dotnet/api/system.single?view=net-7.0)

**Comment by marklio** [comment]
I'm basically 9% sure you're seeing floating point representation error and the difference in representation between single and double precision. The way the parser reads a float is that it pulls the 4 bytes out and interprets this as an IEEE single-precision floating point (that is, the bits are not manipulated in any way). So, -1.8033078 is correct. The "extra precision" that comes from the cast to a double is "fake" and comes from the binary representation. There's no actual hidden precision there.

**Comment by marklio** [comment]
(two's complement  is incorrect). Fixing that commment

**Comment by marklio** [comment]
Had a chance to refresh my memory a bit. The "mantissa" of a single precision floating point number is 23 bits, so that's the most "real" significant digits you can get out of a single-precision.

**Comment by mgoldste1** [comment]
ngl, this hurts my brain and I really don't know what to believe.  I went to the guy that owns our python converter and asked him how his program is creating data beyond what microsoft claims can be stored in 4 bytes and assumed the python one was wrong, but I really dont know what to believe anymore...

If you can save a -1.8033077716827393f to a float, write it out and see its clipped, then cast it to a double and suddenly its back to what it was before?  It's got to be saving the actual data...

**Comment by marklio** [comment]
Pick a different number that long and try to round trip  through that conversion. You've picked a very special number that matches a particular representation difference between single and double. :)

**Comment by marklio** [comment]
I mean, it's really about the conversion from/to decimal representation as well.

**Comment by marklio** [comment]
I mean, you're talking about comparing two sticks that are almost 2 meters long and trying to determine which one is a few atoms taller :)

**Comment by mgoldste1** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mgoldste/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mgoldste/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



LinqToStdf | LinqToStdf        (cast to double) | Python's output
-- | -- | --
-1.8033078 | -1.8033077716827393 | -1.8033077716827393
-1.803288 | -1.8032879829406738 | -1.8032879829406738
-1.8028319 | -1.8028318881988525 | -1.8028318881988525
-1.8008522 | -1.8008521795272827 | -1.8008521795272827
-1.7978286 | -1.7978285551071167 | -1.7978285551071167
-1.8004534 | -1.8004534244537354 | -1.8004534244537354
-1.8012661 | -1.801266074180603 | -1.801266074180603
-1.8033638 | -1.8033638000488281 | -1.8033638000488281
-1.8030145 | -1.8030145168304443 | -1.8030145168304443
-1.8009413 | -1.8009413480758667 | -1.8009413480758667
-1.8026139 | -1.8026138544082642 | -1.8026138544082642
-1.7997268 | -1.7997268438339233 | -1.7997268438339233
-1.8057095 | -1.8057094812393188 | -1.8057094812393188
-1.8005259 | -1.8005259037017822 | -1.8005259037017822
-1.8024378 | -1.8024377822875977 | -1.8024377822875977
-1.8015792 | -1.801579236984253 | -1.801579236984253



</body>

</html>

**Comment by mgoldste1** [comment]
That is picking other numbers. Lol.  It's an exact match every time to what python is saying exists in that field

**Comment by marklio** [comment]
That just means Python is using double-precision as an implementation detail. Take the 4th example and do an experiment:
```
// original value -1.8008521795272827f
float f = -1.8008521795272844f;
f.Dump("single precision");
((double)f).Dump("double precision");
```

This produces:

```
single precision
-1.8008522
double precision
-1.8008521795272827
```

Notice how we got the same original number (not the "new" input value)? The rest of that number (beyond the precision of single-precision) is just representation error. It's not real precision. This is just something you have to live with when using IEEE floating point numbers. They don't convert to decimal cleanly, and single and double precision have different representation error associated with them.

**Comment by mgoldste1** [comment]
Yea, you are right.  I did another test - 

```
string s1 = "-1.8033077716827393f";
float f1 = -1.8033077716827393f;
Console.WriteLine("s1 = " + s1);
Console.WriteLine("f1 = " + f1);
double d1 = (double)f1;
Console.WriteLine("d1 = " + d1);

string s2 = "-1.8033077710000003f";
float f2 = -1.8033077710000003f;
Console.WriteLine("s2 = " + s2);
Console.WriteLine("f2 = " + f2);
double d2 = (double)f2;
Console.WriteLine("d2 = " + d2);
```

that outputs - 
s1 = -1.8033077716827393f
f1 = -1.8033078
d1 = -1.8033077716827393
s2 = -1.8033077710000003f
f2 = -1.8033078
d2 = -1.8033077716827393


the numbers are special. the python code was a special number generator. lol.

**Comment by marklio** [comment]
special number generator = ((double)someFloat).ToString() :)
