### ISSUE TITLE
Slowness when dealing with large stdf files

### ISSUE THREAD

**Issue by mgoldste1** [marklio/LinqToStdf#28]
I started feeding my converter large stdf files (800mb to 1.5gb) and it's got some performance problems.  My code is making a collection of collections containing the records for an individual die.  I've tried a few ways of doing it but it's basically just getting a list of Pirs in the file, then for each one of them it's grabbing that Pir's children and its matching Prr. When you process the first pir, it goes quickly. The first record takes 39ms. The second takes 3.34ms.  By the 10th record, it's taking twice as long (7ms).  By the 4000th Pir record, it's taking 1.5 to 2 seconds.  It took about an hour just to group things up.

Now if you do it in reverse and start with the last Pir record, it starts out super slow and eventually speeds up to 3ms.  I _assume_ that each time you get the children and/or matching prr it's essentially a full table scan.  I was hoping that because I was giving it a Pir record as a starting point, it'd start from there and not the beginning of the file. It seems like the pir.After() has to scan all previous records in the file to find the starting point.

I know looping through the stdf file record by record is relatively quick so I can group things up in a more manual fashion but I was hoping you knew of a way to speed up the build in functionality.

-------------------------------------------------------

More info... in case any of this is useful. lol. My code was originally iterating over the result of this method:

```
public static IEnumerable<IEnumerable<StdfRecord>> GetDieGroupings(this IEnumerable<StdfRecord> source)
        {
            var pirs = source.OfExactType<Pir>();
            return pirs.Select(o => new[] {  Enumerable.Repeat(o, 1),
                                              o.GetChildRecords(),
                                              Enumerable.Repeat(o.GetMatchingPrr()!,1)
                                          }
                                          .SelectMany(o => o));
        }
```

Because the code was slowing down as it went on, I wrote this as a test (note it only gets 25 sets of records) - 

```
public static List<List<StdfRecord>> GetDieGroupingsListWay(this IEnumerable<StdfRecord> source)
        {
            var pirs = source.OfExactType<Pir>().ToList();

            List<List<StdfRecord>> result = new();
            int iterNum = 0;
            foreach (var pir in pirs)
            {
                Log.get.Info("iter #" + iterNum);
                iterNum++;
                List<StdfRecord> dieGrp = new();
                dieGrp.Add(pir);
                dieGrp.AddRange(pir.GetChildRecords().ToList());
                dieGrp.Add(pir.GetMatchingPrr()!);
                result.Add(dieGrp);
                if (iterNum > 25)
                    break;
            }
            return result;
        }
```

When you change the for loop to "foreach (var pir in pirs.OrderByDescending(o => o.Offset))" and run it again, it takes ~60x the time to get the last 25 as it does to get the first 25.

The test code using this method is the following (Note I used the design pattern called "copy/paste" to make a GetDieGroupingsListWay_LastFirst() which has the alternate for loop) - 

```
void PirPerfTest2()
{
    string filename = @"C:\stdf\filename.stdf";
    StdfFile stdfFile = new StdfFile(filename, new V4StructureIndexingStrategy());
    Log.get.Info("Getting records.");
    stdfFile.GetRecords().ToList();
    Log.get.Info("Got the records.");
    Stopwatch sw = Stopwatch.StartNew();
    Log.get.Info("Starting from the first Pir");
    stdfFile.GetRecordsEnumerable().GetDieGroupingsListWay();
    var firstPirTestTime = sw.Elapsed.TotalMilliseconds;
    Log.get.Info("Time taken for first Pir - " + Math.Round(firstPirTestTime, 2) + "ms");
    sw.Restart();
    Log.get.Info("Starting from the last Pir");
    stdfFile.GetRecordsEnumerable().GetDieGroupingsListWay_LastFirst();
    var lastPirTestTime = sw.Elapsed.TotalMilliseconds;
    Log.get.Info("Time taken for first Pir - " + Math.Round(lastPirTestTime, 2) + "ms");
    Log.get.Info("Last Pir took " + Math.Round(lastPirTestTime / firstPirTestTime, 2) + " longer than the first pir.");
    _ = 345;
}
```

Output - 

> 2023-07-06 10:52:27,623; [1]; INFO; - Getting records.
> 2023-07-06 10:53:10,806; [1]; INFO; - Got the records.
> 2023-07-06 10:53:10,806; [1]; INFO; - Starting from the first Pir
> 2023-07-06 10:53:11,195; [1]; INFO; - iter # 0
> 2023-07-06 10:53:11,227; [1]; INFO; - iter # 1
> 2023-07-06 10:53:11,230; [1]; INFO; - iter # 2
> 2023-07-06 10:53:11,234; [1]; INFO; - iter # 3
> 2023-07-06 10:53:11,238; [1]; INFO; - iter # 4
> 2023-07-06 10:53:11,242; [1]; INFO; - iter # 5
> 2023-07-06 10:53:11,247; [1]; INFO; - iter # 6
> 2023-07-06 10:53:11,252; [1]; INFO; - iter # 7
> 2023-07-06 10:53:11,260; [1]; INFO; - iter # 8
> 2023-07-06 10:53:11,266; [1]; INFO; - iter # 9
> 2023-07-06 10:53:11,273; [1]; INFO; - iter # 10
> 2023-07-06 10:53:11,278; [1]; INFO; - iter # 11
> 2023-07-06 10:53:11,284; [1]; INFO; - iter # 12
> 2023-07-06 10:53:11,290; [1]; INFO; - iter # 13
> 2023-07-06 10:53:11,296; [1]; INFO; - iter # 14
> 2023-07-06 10:53:11,304; [1]; INFO; - iter # 15
> 2023-07-06 10:53:11,351; [1]; INFO; - iter # 16
> 2023-07-06 10:53:11,359; [1]; INFO; - iter # 17
> 2023-07-06 10:53:11,367; [1]; INFO; - iter # 18
> 2023-07-06 10:53:11,376; [1]; INFO; - iter # 19
> 2023-07-06 10:53:11,388; [1]; INFO; - iter # 20
> 2023-07-06 10:53:11,397; [1]; INFO; - iter # 21
> 2023-07-06 10:53:11,406; [1]; INFO; - iter # 22
> 2023-07-06 10:53:11,417; [1]; INFO; - iter # 23
> 2023-07-06 10:53:11,428; [1]; INFO; - iter # 24
> 2023-07-06 10:53:11,439; [1]; INFO; - iter # 25
> 2023-07-06 10:53:11,451; [1]; INFO; - Time taken for first Pir - 645.27ms
> 2023-07-06 10:53:11,452; [1]; INFO; - Starting from the last Pir
> 2023-07-06 10:53:11,859; [1]; INFO; - iter # 0
> 2023-07-06 10:53:13,285; [1]; INFO; - iter # 1
> 2023-07-06 10:53:14,718; [1]; INFO; - iter # 2
> 2023-07-06 10:53:16,070; [1]; INFO; - iter # 3
> 2023-07-06 10:53:17,444; [1]; INFO; - iter # 4
> 2023-07-06 10:53:18,830; [1]; INFO; - iter # 5
> 2023-07-06 10:53:20,222; [1]; INFO; - iter # 6
> 2023-07-06 10:53:21,568; [1]; INFO; - iter # 7
> 2023-07-06 10:53:22,977; [1]; INFO; - iter # 8
> 2023-07-06 10:53:24,425; [1]; INFO; - iter # 9
> 2023-07-06 10:53:25,759; [1]; INFO; - iter # 10
> 2023-07-06 10:53:27,115; [1]; INFO; - iter # 11
> 2023-07-06 10:53:28,466; [1]; INFO; - iter # 12
> 2023-07-06 10:53:29,854; [1]; INFO; - iter # 13
> 2023-07-06 10:53:31,255; [1]; INFO; - iter # 14
> 2023-07-06 10:53:32,639; [1]; INFO; - iter # 15
> 2023-07-06 10:53:34,178; [1]; INFO; - iter # 16
> 2023-07-06 10:53:35,875; [1]; INFO; - iter # 17
> 2023-07-06 10:53:37,503; [1]; INFO; - iter # 18
> 2023-07-06 10:53:39,030; [1]; INFO; - iter # 19
> 2023-07-06 10:53:40,587; [1]; INFO; - iter # 20
> 2023-07-06 10:53:42,076; [1]; INFO; - iter # 21
> 2023-07-06 10:53:43,569; [1]; INFO; - iter # 22
> 2023-07-06 10:53:45,015; [1]; INFO; - iter # 23
> 2023-07-06 10:53:46,476; [1]; INFO; - iter # 24
> 2023-07-06 10:53:47,963; [1]; INFO; - iter # 25
> ...(hit a breakpoint but the stop watch's time was saved before the breakpoint so the number below is accurate.)
> 2023-07-06 10:56:42,290; [1]; INFO; - Time taken for first Pir - 38006.79ms
> 2023-07-06 10:56:42,696; [1]; INFO; - Last Pir took 58.9 longer than the first pir.

I tried the V4 index strat and the simple one.  It doesn't make a difference.  The no cache one bugs out and the GetRecordsInternal ends up with a null stream towards the end of the stdf file, but I haven't had a chance to look at that much.  

I also tried feeding GetDieGroupingsListWay the following variations as an input but it made no difference - 
- the initial stdfFile.GetRecords().ToList()
- the stdfFile.GetRecordEnumerable().ToList()
- stdfFile.GetRecordEnumerable()

I figured doing a stdfFile.GetRecords().ToList() before the stopwatch started would load the records into ram and not affect the time taken in the tests.

Some more logs from a new test I am running... it shows the time taken for each step- 

```
2023-07-06 12:39:19,368; [1]; INFO; - Pir Offset is 1325428601
2023-07-06 12:39:19,369; [1]; INFO; - Getting children
2023-07-06 12:39:20,207; [1]; INFO; - Getting Prr
2023-07-06 12:39:20,977; [1]; INFO; - Populating List
2023-07-06 12:39:20,978; [1]; INFO; - Die Group Record Count: 3292; Time taken - 1609.4ms
2023-07-06 12:39:20,978; [1]; INFO; - Pir Offset is 1325428595
2023-07-06 12:39:20,978; [1]; INFO; - Getting children
2023-07-06 12:39:21,849; [1]; INFO; - Getting Prr
2023-07-06 12:39:22,760; [1]; INFO; - Populating List
2023-07-06 12:39:22,760; [1]; INFO; - Die Group Record Count: 3292; Time taken - 1782.1ms
2023-07-06 12:39:22,760; [1]; INFO; - Pir Offset is 1325428589
2023-07-06 12:39:22,761; [1]; INFO; - Getting children
2023-07-06 12:39:23,597; [1]; INFO; - Getting Prr
2023-07-06 12:39:24,420; [1]; INFO; - Populating List
2023-07-06 12:39:24,420; [1]; INFO; - Die Group Record Count: 3292; Time taken - 1659.77ms
2023-07-06 12:39:24,420; [1]; INFO; - Pir Offset is 1325428583
2023-07-06 12:39:24,421; [1]; INFO; - Getting children
2023-07-06 12:39:25,285; [1]; INFO; - Getting Prr
2023-07-06 12:39:26,078; [1]; INFO; - Populating List
2023-07-06 12:39:26,078; [1]; INFO; - Die Group Record Count: 3292; Time taken - 1657.79ms
2023-07-06 12:39:26,078; [1]; INFO; - Pir Offset is 1325428577
2023-07-06 12:39:26,079; [1]; INFO; - Getting children
2023-07-06 12:39:26,861; [1]; INFO; - Getting Prr
2023-07-06 12:39:27,686; [1]; INFO; - Populating List
2023-07-06 12:39:27,687; [1]; INFO; - Die Group Record Count: 3292; Time taken - 1608.37ms
2023-07-06 12:39:27,687; [1]; INFO; - Pir Offset is 1323844361
2023-07-06 12:39:27,687; [1]; INFO; - Getting children
2023-07-06 12:39:28,449; [1]; INFO; - Getting Prr
2023-07-06 12:39:29,319; [1]; INFO; - Populating List
2023-07-06 12:39:29,319; [1]; INFO; - Die Group Record Count: 3292; Time taken - 1632.33ms
```

BTW, I asked the guys on the floor that generate our stdf files if they can make a big one with bogus data.  They think they can, so I might actually be able to get you some stdf files to play with. They are busy today though...

**Comment by marklio** [comment]
I haven't had time to digest this whole thing, but I'm going on vacation soon and may not get back to this until I'm back. The way that you're peeling everything out as IEnumerable and doing your own lists is bypassing the automatic indexing/speedups built into V4StructureIndexingStrategy. It's possible that everything will kick in if you use GetRecords() and pass IQueryable<StdfRecord> around rather than IEnumerable<StdfRecord>. V4StructureIndexingStrategy indexes the locations of PIR/PRR pairs and makes GetChildRecords very fast (because it knows the range of child records and only has to filter by head/site), but IQueryable is the mechanism that it uses to optimize the calls (it switches out calls to GetChildRecords() to V4StructureIndexingStrategy.GetChildRecords().

**Comment by mgoldste1** [comment]
If I hear back again thanks in advanced. :)

Ok so I think we can simplify the problem statement with this information.  I can't seem to get it to actually use the strategy I tell it too.

I downloaded a fresh copy of the code (.net 7 branch downgraded to .net 6) and ran the following - 

```
StdfFile stdfFile = new StdfFile(filename);
            stdfFile.IndexingStrategy = new V4StructureIndexingStrategy();
            var AllPirs = stdfFile.GetRecords().OfExactType<Pir>().OrderBy(o => o.Offset);
            List<List<StdfRecord>> recs = new();
            int i = 0;
            foreach(var Pir in AllPirs)
            {
                Stopwatch sw = Stopwatch.StartNew();
                i++;
                Console.WriteLine("Start of Pir # " + i);
                List<StdfRecord> dieRecs = new();
                dieRecs.Add(Pir);
                Console.WriteLine("Getting children");
                dieRecs.AddRange(Pir.GetChildRecords());
                Console.WriteLine("Getting prr");
                dieRecs.Add(Pir.GetMatchingPrr()!);
                Console.WriteLine("Getting add to main list");
                recs.Add(dieRecs);
                Console.WriteLine("================================= Time taken: " + sw.ElapsedMilliseconds + " ms =========================");
            }
```

With this, the all pirs is now an IOrderedQueriably so I assume it's using the strategy, but when I call Pir.GetChildRecords() it is not going to the v4 strategy's version of the method.  It's going to the main one in the extensions.

How do I get it to go to the strategy's version?


edit: i put breakpoints into the v4 strategy versions of the code and they did not trigger.

**Comment by marklio** [comment]
OK, for it to get rewritten to use the strategy, it all needs to happen in the context of the IQueryable. You could do something like the following (I haven't compiled this, but this should work):
```
var parts = (from pirs in stdfFile.GetRecords().OfExactType<Pir>()
orderby pirs o.Offset //although this shouldn't be necessary
select new {
  Pir = pir,
  Children = pir.GetChildRecords().ToList(),
  Prr = prr,
}).ToList();
```
Now, you have "basically" the same thing your code builds, but it should pop out the end MUCH faster.

I should consider if there's a better approach to wire the strategy in without the need for the crazy IQueryable nonsense. The idea was that an analyzer could look at the query and optimize it (ex. if the query uses x and y data, it could index by that and make wafermaps really fast)

**Comment by mgoldste1** [comment]
Welp, that just processed 14.2 million records in 11 seconds.  To put that in perspective, that is about a 327x performance gain.

This was the final code that compiled and worked.

            StdfFile stdfFile = new StdfFile(filename);
            stdfFile.IndexingStrategy = new V4StructureIndexingStrategy();
            log("reading in file");
            var all = stdfFile.GetRecords().ToList();//.OfExactType<Pir>().OrderBy(o => o.Offset);


            //Stopwatch sw2 = Stopwatch.StartNew();
            log("Start of Mark's way");
            var parts = (from pirs in stdfFile.GetRecords().OfExactType<Pir>()
                         //orderby pirs.Offset //although this shouldn't be necessary
                         select new
                         {
                             Pir = pirs,
                             Children = pirs.GetChildRecords().ToList(),
                             Prr = pirs.GetMatchingPrr(),
                         }).ToList();
            log("end of Mark's way, start of altered version");
            var partsv2 = stdfFile.GetRecords().OfExactType<Pir>()
                                               .Select(o=> new {o, kids = o.GetChildRecords().ToList(), prr =  o.GetMatchingPrr()})
                                               .ToList();
            log("end of altered version");

            var qnt = parts.Sum(o => o.Children.Count + 2);
            log("num records organized - " + qnt);

Output:
```

15:50:23.333: reading in file
15:50:59.692: Start of Mark's way
15:51:12.579: end of Mark's way, start of altered version
15:51:23.514: end of altered version
15:51:23.515: num records organized - 14225758
```

I changed the format of the linq statement just because that's the style I'm used to.

It's also using 2gb less ram now. Neat.

Hopefully you won't hear from me for a while! Lol.  If I get an stdf file you can play around with, I'll shoot you an email.

**Comment by marklio** [comment]
Great! I'm going to close this issue.
