### ISSUE TITLE
Instead of file path

### ISSUE THREAD

**Issue by kmuthugtk** [marklio/LinqToStdf#33]
Instead of file path, is it possible to use file byte array to the StdfFile class?

Because I am monitoring the continuously like every 2 seconds. So that time File is too busy.

So I am prefer to use the file byte. Can you help me

**Comment by marklio** [comment]
You can implement IStdfStreamManager and provide a Stream over any underlying storage you'd like. You can look at https://github.com/marklio/LinqToStdf/blob/master/Main/LinqToStdf/StreamManager.cs to see how this is done. All of the underlying file access is done via an IStdfStreamManager implementation. it would be pretty easy to do this over a byte array.
